// Mock artists — includes full profile data for ArtistDetail page
export const mockArtists = [
  {
    id: 1,
    name: "Alex Jeannn",
    email: "alex@email.com",
    phone: "+94 77 123 4567",
    category: "Musician",
    location: "Colombo",
    bookings: 47,
    rating: 4.7,
    reviewCount: 151,
    status: "verified",
    avatar: "https://i.pravatar.cc/150?img=1",
    coverImage:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=900&q=80",
    joinedDate: "Jan 2025",
    bio: "Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsu",
    tags: ["artist", "indoor", "party", "indoor"],
    basePrice: 800,
    priceRange: "LKR 800 – LKR 3,500 depending on event type and duration",
    ageLimit: "13+",
    genres: ["Pop", "R&B", "Soul"],
    overview:
      "Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsu\n\nLorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsu\n\nLorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit amet.",
    gallery: [
      "https://images.unsplash.com/photo-1501386761578-eaa54b7a0e1f?w=400&q=80",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80",
    ],
    media: [
      {
        id: 1,
        title:
          "Live in Concert Colombo (Lorem ipsum dolor sit amet, consectetur )",
        type: "youtube",
      },
      {
        id: 2,
        title:
          "Live in Concert Colombo (Lorem ipsum dolor sit amet, consectetur )",
        type: "spotify",
      },
      {
        id: 3,
        title:
          "Live in Concert Colombo (Lorem ipsum dolor sit amet, consectetur )",
        type: "spotify",
      },
      {
        id: 4,
        title:
          "Live in Concert Colombo (Lorem ipsum dolor sit amet, consectetur )",
        type: "spotify",
      },
    ],
    socials: { apple: "#", facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 382,500",
    completionRate: 94,
    suspendReason: null,
    pendingNote: null,
  },
  {
    id: 2,
    name: "Nirmala Kumari",
    email: "nirmala@email.com",
    phone: "+94 77 456 7890",
    category: "Singer",
    location: "Kandy",
    bookings: 32,
    rating: 4.5,
    reviewCount: 89,
    status: "verified",
    avatar: "https://i.pravatar.cc/150?img=5",
    coverImage:
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=900&q=80",
    joinedDate: "Feb 2025",
    bio: "Professional singer with 10+ years of experience in classical and contemporary music.",
    tags: ["singer", "classical", "wedding", "events"],
    basePrice: 600,
    priceRange: "LKR 600 – LKR 2,500 depending on event type and duration",
    ageLimit: "All ages",
    genres: ["Classical", "Pop", "Baila"],
    overview:
      "Nirmala is a seasoned vocalist performing across Sri Lanka at weddings, corporate events, and concerts.\n\nWith training in both classical and contemporary styles, she adapts to every stage and audience seamlessly.\n\nAvailable for solo performances and full band collaborations.",
    gallery: [
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80",
    ],
    media: [
      { id: 1, title: "Wedding Performance Kandy 2025", type: "youtube" },
      { id: 2, title: "Classical Night Live", type: "spotify" },
    ],
    socials: { apple: "#", facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 214,000",
    completionRate: 98,
    suspendReason: null,
    pendingNote: null,
  },
  {
    id: 3,
    name: "DJ Pulse",
    email: "djpulse@email.com",
    phone: "+94 76 333 9999",
    category: "DJ",
    location: "Galle",
    bookings: 61,
    rating: 4.9,
    reviewCount: 210,
    status: "pending",
    avatar: "https://i.pravatar.cc/150?img=3",
    coverImage:
      "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=900&q=80",
    joinedDate: "Mar 2025",
    bio: "High-energy DJ specialising in EDM, house, and commercial beats for clubs and private events.",
    tags: ["dj", "edm", "club", "party"],
    basePrice: 1200,
    priceRange: "LKR 1,200 – LKR 5,000 depending on event type and duration",
    ageLimit: "18+",
    genres: ["EDM", "House", "Commercial"],
    overview:
      "DJ Pulse has performed at over 60 events across the southern coast.\n\nSubmitted for verification on March 10, 2026. Documents and portfolio currently under admin review.\n\nProfile will go live once approved.",
    gallery: [
      "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=400&q=80",
    ],
    media: [
      { id: 1, title: "Club Night Mix — Galle Fort 2025", type: "spotify" },
    ],
    socials: { apple: "#", facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 0",
    completionRate: 0,
    suspendReason: null,
    pendingNote:
      "Application submitted March 10, 2026. NIC and bank statement uploaded. Awaiting admin review.",
    verificationData: {
      submittedDate: "March 10, 2026",
      profile: {
        fullName: "Pulse Devin Fernando",
        nic: "199312345678V",
        phone: "+94 76 333 9999",
        category: "DJ",
        location: "Galle",
        dateOfBirth: "March 15, 1993",
        genres: "EDM, House, Commercial",
      },
      documents: [
        { label: "National ID", uploaded: true },
        { label: "Passport", uploaded: false },
        { label: "Bank Statement", uploaded: true },
        { label: "Driving License", uploaded: false },
      ],
      portfolio: {
        images: [
          "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=400&q=80",
          "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80",
          "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&q=80",
        ],
        video: true,
      },
      pricing: {
        basePrice: 1200,
        pricePerHour: 800,
        addOns: ["Sound System (+LKR 3,000)", "Travel > 50km (+LKR 500)"],
      },
      travelRadius: 80,
      socialLinks: {
        instagram: "https://instagram.com/djpulse",
        facebook: "https://facebook.com/djpulse",
        youtube: "https://youtube.com/@djpulse",
        spotify: null,
      },
    },
  },
  {
    id: 4,
    name: "Sarah Bands",
    email: "sarah@email.com",
    phone: "+94 71 777 2222",
    category: "Band",
    location: "Colombo",
    bookings: 18,
    rating: 4.2,
    reviewCount: 44,
    status: "suspended",
    avatar: "https://i.pravatar.cc/150?img=9",
    coverImage:
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=900&q=80",
    joinedDate: "Dec 2024",
    bio: "Live band covering pop, rock, and retro hits for parties and corporate events.",
    tags: ["band", "live", "rock", "pop"],
    basePrice: 2000,
    priceRange: "LKR 2,000 – LKR 8,000 depending on event type and duration",
    ageLimit: "All ages",
    genres: ["Rock", "Pop", "Retro"],
    overview:
      "Sarah Bands is a 5-piece live band known for high energy performances.\n\nCurrently suspended pending investigation into a payment dispute with a customer.\n\nAccount restricted until further review by admin.",
    gallery: [
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&q=80",
    ],
    media: [],
    socials: { apple: "#", facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 148,000",
    completionRate: 78,
    suspendReason:
      "Multiple customer complaints regarding late cancellations and payment disputes reported on March 2, 2026.",
    pendingNote: null,
  },
  {
    id: 5,
    name: "MC Royal",
    email: "mcroyal@email.com",
    phone: "+94 70 555 8888",
    category: "MC",
    location: "Negombo",
    bookings: 55,
    rating: 4.8,
    reviewCount: 178,
    status: "verified",
    avatar: "https://i.pravatar.cc/150?img=6",
    coverImage:
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=900&q=80",
    joinedDate: "Nov 2024",
    bio: "Professional MC and host for weddings, corporate events, award shows and concerts.",
    tags: ["mc", "host", "wedding", "corporate"],
    basePrice: 500,
    priceRange: "LKR 500 – LKR 2,000 depending on event type and duration",
    ageLimit: "All ages",
    genres: ["Hosting", "Bilingual", "Sinhala", "English"],
    overview:
      "MC Royal brings energy and professionalism to every event.\n\nFluent in Sinhala and English, available island-wide.\n\nSpecialises in wedding receptions, corporate award nights, and live concert hosting.",
    gallery: [
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&q=80",
    ],
    media: [
      { id: 1, title: "Award Night Hosting — Hilton Colombo", type: "youtube" },
      { id: 2, title: "Wedding MC Highlights 2025", type: "youtube" },
    ],
    socials: { apple: "#", facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 276,000",
    completionRate: 97,
    suspendReason: null,
    pendingNote: null,
  },
  {
    id: 6,
    name: "Priya Dance",
    email: "priya@email.com",
    phone: "+94 77 888 3333",
    category: "Dance",
    location: "Colombo",
    bookings: 29,
    rating: 4.6,
    reviewCount: 67,
    status: "pending",
    avatar: "https://i.pravatar.cc/150?img=10",
    coverImage:
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=900&q=80",
    joinedDate: "Apr 2025",
    bio: "Contemporary and classical dance performer for stage shows and events.",
    tags: ["dance", "contemporary", "classical", "stage"],
    basePrice: 700,
    priceRange: "LKR 700 – LKR 3,000 depending on event type and duration",
    ageLimit: "All ages",
    genres: ["Contemporary", "Classical", "Bollywood"],
    overview:
      "Priya is a trained contemporary and classical dance artist.\n\nApplication submitted April 2, 2026. Portfolio includes 3 performance videos and stage photos.\n\nAwaiting admin verification.",
    gallery: [],
    media: [
      { id: 1, title: "Stage Show — Nelum Pokuna 2025", type: "youtube" },
    ],
    socials: { facebook: "#", instagram: "#" },
    totalEarnings: "LKR 0",
    completionRate: 0,
    suspendReason: null,
    pendingNote:
      "Application submitted April 2, 2026. Portfolio uploaded. Awaiting admin review.",
    verificationData: {
      submittedDate: "April 2, 2026",
      profile: {
        fullName: "Priya Malshani",
        nic: "200056789012V",
        phone: "+94 77 888 3333",
        category: "Dance",
        location: "Colombo",
        dateOfBirth: "July 22, 2000",
        genres: "Contemporary, Classical, Bollywood",
      },
      documents: [
        { label: "National ID", uploaded: true },
        { label: "Passport", uploaded: true },
        { label: "Bank Statement", uploaded: false },
        { label: "Driving License", uploaded: false },
      ],
      portfolio: {
        images: [
          "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80",
          "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80",
        ],
        video: true,
      },
      pricing: {
        basePrice: 700,
        pricePerHour: 500,
        addOns: ["Costume (+LKR 1,500)", "Travel > 30km (+LKR 300)"],
      },
      travelRadius: 50,
      socialLinks: {
        instagram: "https://instagram.com/priyadance",
        facebook: null,
        youtube: "https://youtube.com/@priyadance",
        spotify: null,
      },
    },
  },
  {
    id: 7,
    name: "Light Show Pro",
    email: "lights@email.com",
    phone: "+94 76 111 4444",
    category: "Lighting",
    location: "Matara",
    bookings: 43,
    rating: 4.4,
    reviewCount: 102,
    status: "verified",
    avatar: "https://i.pravatar.cc/150?img=7",
    coverImage:
      "https://images.unsplash.com/photo-1493863641943-9b68992a8d07?w=900&q=80",
    joinedDate: "Jan 2025",
    bio: "Professional lighting and stage design for concerts, weddings, and corporate events.",
    tags: ["lighting", "stage", "events", "professional"],
    basePrice: 1500,
    priceRange: "LKR 1,500 – LKR 6,000 depending on event type and duration",
    ageLimit: "All ages",
    genres: ["Concert Lighting", "Wedding Decor", "Stage Design"],
    overview:
      "Light Show Pro provides full lighting rigs and stage design services across southern Sri Lanka.\n\nEquipment includes LED arrays, moving heads, haze machines, and laser systems.\n\nAvailable island-wide for large-scale events.",
    gallery: [
      "https://images.unsplash.com/photo-1493863641943-9b68992a8d07?w=400&q=80",
      "https://images.unsplash.com/photo-1504199367641-aba8151af406?w=400&q=80",
    ],
    media: [
      {
        id: 1,
        title: "Concert Rig Setup — Galle International Stadium",
        type: "youtube",
      },
    ],
    socials: { facebook: "#", instagram: "#" },
    totalEarnings: "LKR 327,000",
    completionRate: 91,
    suspendReason: null,
    pendingNote: null,
  },
  {
    id: 8,
    name: "Rock Nation",
    email: "rock@email.com",
    phone: "+94 71 222 7777",
    category: "Band",
    location: "Colombo",
    bookings: 22,
    rating: 4.3,
    reviewCount: 58,
    status: "verified",
    avatar: "https://i.pravatar.cc/150?img=8",
    coverImage:
      "https://images.unsplash.com/photo-1468164016595-6108e4c60c8b?w=900&q=80",
    joinedDate: "Feb 2025",
    bio: "Hard rock and metal band performing originals and covers at venues across Colombo.",
    tags: ["rock", "metal", "band", "live"],
    basePrice: 2500,
    priceRange: "LKR 2,500 – LKR 9,000 depending on event type and duration",
    ageLimit: "16+",
    genres: ["Hard Rock", "Metal", "Alternative"],
    overview:
      "Rock Nation is Colombo's premier hard rock act, performing originals and classic covers.\n\nRegular performers at Barefoot, The Music Room, and BMICH concerts.\n\nAvailable for private events, festivals, and venue residencies.",
    gallery: [
      "https://images.unsplash.com/photo-1468164016595-6108e4c60c8b?w=400&q=80",
    ],
    media: [
      { id: 1, title: "Live at The Music Room Colombo", type: "youtube" },
      { id: 2, title: 'Original Track — "Island Fire"', type: "spotify" },
    ],
    socials: { facebook: "#", instagram: "#", spotify: "#" },
    totalEarnings: "LKR 198,000",
    completionRate: 86,
    suspendReason: null,
    pendingNote: null,
  },
];

// Mock verification applications
export const mockVerifications = [
  {
    id: 1,
    name: "Nirmala Kumari",
    category: "Singer",
    location: "Colombo",
    submittedDate: "March 3, 2026",
    avatar: "https://i.pravatar.cc/40?img=5",
    status: "pending",
    isToday: true,
    isResubmitted: false,
    profile: {
      fullName: "Nirmala Kumari",
      stageName: "Nirmala K",
      nic: "987654321V",
      phone: "+94 77 456 7890",
      email: "nirmala@email.com",
      category: "Singer",
      location: "Colombo",
      dateOfBirth: "June 12, 1995",
      genres: "Pop, Classical, Baila",
    },
    documents: [
      { label: "National ID", uploaded: true },
      { label: "Passport", uploaded: true },
      { label: "Bank Statement", uploaded: true },
      { label: "Driving License", uploaded: false },
    ],
    portfolio: {
      images: [
        "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80",
        "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80",
        "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80",
      ],
      video: true,
    },
    pricing: {
      basePrice: 600,
      pricePerHour: 400,
      addOns: ["Sound System (+LKR 2,000)", "Travel > 40km (+LKR 400)"],
    },
    travelRadius: 60,
    socialLinks: {
      instagram: "https://instagram.com/nirmala_k",
      facebook: "https://facebook.com/nirmalakumari",
      youtube: "https://youtube.com/@nirmalak",
      spotify: null,
    },
  },
  {
    id: 2,
    name: "Kamal Silva",
    category: "Singer",
    location: "Colombo",
    submittedDate: "March 3, 2026",
    avatar: "https://i.pravatar.cc/40?img=11",
    status: "pending",
    isToday: true,
    isResubmitted: false,
    profile: {
      fullName: "Kamal Silva",
      stageName: "K. Silva",
      nic: "123456789V",
      phone: "+94 71 234 5678",
      email: "kamal@email.com",
      category: "Singer",
      location: "Colombo",
      dateOfBirth: "January 8, 1992",
      genres: "R&B, Soul",
    },
    documents: [
      { label: "National ID", uploaded: true },
      { label: "Passport", uploaded: false },
      { label: "Bank Statement", uploaded: true },
      { label: "Driving License", uploaded: false },
    ],
    portfolio: {
      images: [
        "https://images.unsplash.com/photo-1501386761578-eaa54b7a0e1f?w=400&q=80",
      ],
      video: true,
    },
    pricing: {
      basePrice: 500,
      pricePerHour: 300,
      addOns: ["Travel > 30km (+LKR 300)"],
    },
    travelRadius: 40,
    socialLinks: {
      instagram: "https://instagram.com/kamalsilva",
      facebook: null,
      youtube: null,
      spotify: "https://open.spotify.com/artist/kamalsilva",
    },
  },
  {
    id: 3,
    name: "Tharindu Perera",
    category: "DJ",
    location: "Negombo",
    submittedDate: "March 3, 2026",
    avatar: "https://i.pravatar.cc/40?img=12",
    status: "pending",
    isToday: false,
    isResubmitted: true,
    profile: {
      fullName: "Tharindu Perera",
      stageName: "DJ Tharindu",
      nic: "456789123V",
      phone: "+94 76 345 6789",
      email: "tharindu@email.com",
      category: "DJ",
      location: "Negombo",
      dateOfBirth: "September 30, 1998",
      genres: "EDM, House, Trap",
    },
    documents: [
      { label: "National ID", uploaded: true },
      { label: "Passport", uploaded: true },
      { label: "Bank Statement", uploaded: false },
      { label: "Driving License", uploaded: false },
    ],
    portfolio: {
      images: [
        "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=400&q=80",
        "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80",
      ],
      video: true,
    },
    pricing: {
      basePrice: 1000,
      pricePerHour: 700,
      addOns: ["Sound System (+LKR 2,500)", "Lighting (+LKR 1,500)"],
    },
    travelRadius: 70,
    socialLinks: {
      instagram: "https://instagram.com/djtharindu",
      facebook: "https://facebook.com/djtharindu",
      youtube: null,
      spotify: null,
    },
  },
  {
    id: 4,
    name: "Amaya Fernando",
    category: "Dancer",
    location: "Kandy",
    submittedDate: "March 3, 2026",
    avatar: "https://i.pravatar.cc/40?img=13",
    status: "pending",
    isToday: false,
    isResubmitted: true,
    profile: {
      fullName: "Amaya Fernando",
      stageName: "Amaya Dance",
      nic: "789123456V",
      phone: "+94 70 456 7890",
      email: "amaya@email.com",
      category: "Dancer",
      location: "Kandy",
      dateOfBirth: "March 5, 2001",
      genres: "Contemporary, Kandyan, Bollywood",
    },
    documents: [
      { label: "National ID", uploaded: true },
      { label: "Passport", uploaded: false },
      { label: "Bank Statement", uploaded: false },
      { label: "Driving License", uploaded: false },
    ],
    portfolio: {
      images: [
        "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&q=80",
        "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80",
        "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&q=80",
      ],
      video: true,
    },
    pricing: {
      basePrice: 700,
      pricePerHour: 500,
      addOns: ["Costume (+LKR 1,500)"],
    },
    travelRadius: 50,
    socialLinks: {
      instagram: "https://instagram.com/amayadance",
      facebook: null,
      youtube: "https://youtube.com/@amayadance",
      spotify: null,
    },
  },
  {
    id: 5,
    name: "Ruwan Jayawardena",
    category: "Band",
    location: "Galle",
    submittedDate: "March 3, 2026",
    avatar: "https://i.pravatar.cc/40?img=14",
    status: "pending",
    isToday: false,
    isResubmitted: false,
    profile: {
      fullName: "Ruwan Jayawardena",
      stageName: "Ruwan & The Band",
      nic: "321654987V",
      phone: "+94 75 567 8901",
      email: "ruwan@email.com",
      category: "Band",
      location: "Galle",
      dateOfBirth: "November 14, 1990",
      genres: "Rock, Pop, Covers",
    },
    documents: [
      { label: "National ID", uploaded: true },
      { label: "Passport", uploaded: false },
      { label: "Bank Statement", uploaded: true },
      { label: "Driving License", uploaded: true },
    ],
    portfolio: {
      images: [
        "https://images.unsplash.com/photo-1468164016595-6108e4c60c8b?w=400&q=80",
      ],
      video: true,
    },
    pricing: {
      basePrice: 2000,
      pricePerHour: 1200,
      addOns: ["Sound System (+LKR 3,000)", "Travel > 50km (+LKR 600)"],
    },
    travelRadius: 90,
    socialLinks: {
      instagram: null,
      facebook: "https://facebook.com/ruwanband",
      youtube: "https://youtube.com/@ruwanband",
      spotify: null,
    },
  },
];

// Mock customers
export const mockCustomers = [
  {
    id: 1,
    name: "Alex Jeannn",
    email: "alex@email.com",
    joined: "Jan 2026",
    bookings: 7,
    totalSpent: "LKR 47,000",
    lastActive: "2h ago",
    status: "active",
    avatar: "https://i.pravatar.cc/150?img=20",
    bookingHistory: [
      {
        id: "#BK-2841",
        artist: "Nirmala Kumari",
        artistAvatar: "https://i.pravatar.cc/40?img=5",
        category: "Singer",
        date: "Mar 28, 2026",
        location: "Colombo",
        amount: "LKR 12,000",
        status: "confirmed",
      },
      {
        id: "#BK-2790",
        artist: "DJ Pulse",
        artistAvatar: "https://i.pravatar.cc/40?img=3",
        category: "DJ",
        date: "Feb 14, 2026",
        location: "Galle",
        amount: "LKR 8,500",
        status: "completed",
      },
      {
        id: "#BK-2745",
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        category: "MC",
        date: "Jan 22, 2026",
        location: "Colombo",
        amount: "LKR 5,000",
        status: "completed",
      },
      {
        id: "#BK-2700",
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        category: "Band",
        date: "Jan 5, 2026",
        location: "Colombo",
        amount: "LKR 9,500",
        status: "completed",
      },
      {
        id: "#BK-2660",
        artist: "Light Show Pro",
        artistAvatar: "https://i.pravatar.cc/40?img=7",
        category: "Lighting",
        date: "Dec 18, 2025",
        location: "Matara",
        amount: "LKR 6,000",
        status: "cancelled",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "DJ Pulse",
        artistAvatar: "https://i.pravatar.cc/40?img=3",
        rating: 5,
        comment:
          "Amazing energy! The whole crowd loved it. Would book again without hesitation.",
        date: "Feb 15, 2026",
      },
      {
        id: 2,
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        rating: 4,
        comment:
          "Very professional and kept the event on schedule. Great crowd engagement.",
        date: "Jan 23, 2026",
      },
      {
        id: 3,
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        rating: 5,
        comment:
          "Best live band we've had at our event. Guests were blown away!",
        date: "Jan 6, 2026",
      },
    ],
  },
  {
    id: 2,
    name: "Samantha Lee",
    email: "sam@email.com",
    joined: "Feb 2026",
    bookings: 3,
    totalSpent: "LKR 21,000",
    lastActive: "1d ago",
    status: "active",
    avatar: "https://i.pravatar.cc/150?img=21",
    bookingHistory: [
      {
        id: "#BK-2840",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Apr 2, 2026",
        location: "Colombo",
        amount: "LKR 8,500",
        status: "pending",
      },
      {
        id: "#BK-2800",
        artist: "Nirmala Kumari",
        artistAvatar: "https://i.pravatar.cc/40?img=5",
        category: "Singer",
        date: "Mar 10, 2026",
        location: "Kandy",
        amount: "LKR 7,000",
        status: "completed",
      },
      {
        id: "#BK-2755",
        artist: "Priya Dance",
        artistAvatar: "https://i.pravatar.cc/40?img=10",
        category: "Dance",
        date: "Feb 20, 2026",
        location: "Colombo",
        amount: "LKR 5,500",
        status: "completed",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "Nirmala Kumari",
        artistAvatar: "https://i.pravatar.cc/40?img=5",
        rating: 5,
        comment:
          "Absolutely stunning performance at our wedding. Everyone was in tears.",
        date: "Mar 11, 2026",
      },
      {
        id: 2,
        artist: "Priya Dance",
        artistAvatar: "https://i.pravatar.cc/40?img=10",
        rating: 4,
        comment:
          "Graceful and captivating. Our guests loved every moment of the show.",
        date: "Feb 21, 2026",
      },
    ],
  },
  {
    id: 3,
    name: "Rajan Patel",
    email: "rajan@email.com",
    joined: "Dec 2025",
    bookings: 12,
    totalSpent: "LKR 98,000",
    lastActive: "5h ago",
    status: "active",
    avatar: "https://i.pravatar.cc/150?img=22",
    bookingHistory: [
      {
        id: "#BK-2839",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Mar 20, 2026",
        location: "Colombo",
        amount: "LKR 15,000",
        status: "completed",
      },
      {
        id: "#BK-2810",
        artist: "Light Show Pro",
        artistAvatar: "https://i.pravatar.cc/40?img=7",
        category: "Lighting",
        date: "Mar 5, 2026",
        location: "Matara",
        amount: "LKR 12,000",
        status: "completed",
      },
      {
        id: "#BK-2780",
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        category: "Band",
        date: "Feb 28, 2026",
        location: "Colombo",
        amount: "LKR 18,000",
        status: "completed",
      },
      {
        id: "#BK-2750",
        artist: "DJ Pulse",
        artistAvatar: "https://i.pravatar.cc/40?img=3",
        category: "DJ",
        date: "Feb 10, 2026",
        location: "Galle",
        amount: "LKR 9,500",
        status: "completed",
      },
      {
        id: "#BK-2720",
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        category: "MC",
        date: "Jan 30, 2026",
        location: "Colombo",
        amount: "LKR 5,000",
        status: "completed",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        rating: 5,
        comment:
          "Top notch musician. The guests couldn't stop talking about the performance.",
        date: "Mar 21, 2026",
      },
      {
        id: 2,
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        rating: 4,
        comment:
          "High energy and very professional. Perfect for our corporate night.",
        date: "Mar 1, 2026",
      },
      {
        id: 3,
        artist: "Light Show Pro",
        artistAvatar: "https://i.pravatar.cc/40?img=7",
        rating: 5,
        comment:
          "The lighting setup was breathtaking. Made the whole venue look spectacular.",
        date: "Mar 6, 2026",
      },
      {
        id: 4,
        artist: "DJ Pulse",
        artistAvatar: "https://i.pravatar.cc/40?img=3",
        rating: 3,
        comment:
          "Good performance but started 30 mins late. Music selection was solid though.",
        date: "Feb 11, 2026",
      },
    ],
  },
  {
    id: 4,
    name: "Kavya Nair",
    email: "kavya@email.com",
    joined: "Nov 2025",
    bookings: 1,
    totalSpent: "LKR 6,000",
    lastActive: "3d ago",
    status: "banned",
    avatar: "https://i.pravatar.cc/150?img=23",
    banReason:
      "Fraudulent payment dispute filed on March 2, 2026. Customer reversed charge after event completed.",
    bookingHistory: [
      {
        id: "#BK-2838",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Mar 15, 2026",
        location: "Colombo",
        amount: "LKR 6,000",
        status: "cancelled",
      },
    ],
    reviews: [],
  },
  {
    id: 5,
    name: "Tom Wilson",
    email: "tom@email.com",
    joined: "Mar 2026",
    bookings: 5,
    totalSpent: "LKR 34,000",
    lastActive: "30m ago",
    status: "active",
    avatar: "https://i.pravatar.cc/150?img=24",
    bookingHistory: [
      {
        id: "#BK-2837",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Mar 30, 2026",
        location: "Kandy",
        amount: "LKR 10,000",
        status: "confirmed",
      },
      {
        id: "#BK-2820",
        artist: "Nirmala Kumari",
        artistAvatar: "https://i.pravatar.cc/40?img=5",
        category: "Singer",
        date: "Mar 18, 2026",
        location: "Colombo",
        amount: "LKR 8,000",
        status: "completed",
      },
      {
        id: "#BK-2795",
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        category: "MC",
        date: "Mar 8, 2026",
        location: "Colombo",
        amount: "LKR 5,000",
        status: "completed",
      },
      {
        id: "#BK-2770",
        artist: "DJ Pulse",
        artistAvatar: "https://i.pravatar.cc/40?img=3",
        category: "DJ",
        date: "Mar 1, 2026",
        location: "Galle",
        amount: "LKR 7,000",
        status: "completed",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "Nirmala Kumari",
        artistAvatar: "https://i.pravatar.cc/40?img=5",
        rating: 5,
        comment:
          "She lit up the whole room. Amazing vocal range and stage presence.",
        date: "Mar 19, 2026",
      },
      {
        id: 2,
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        rating: 4,
        comment:
          "Great MC, kept the energy up all night. Very witty and engaging.",
        date: "Mar 9, 2026",
      },
    ],
  },
  {
    id: 6,
    name: "Priya Menon",
    email: "priya@email.com",
    joined: "Jan 2026",
    bookings: 8,
    totalSpent: "LKR 52,000",
    lastActive: "12h ago",
    status: "active",
    avatar: "https://i.pravatar.cc/150?img=25",
    bookingHistory: [
      {
        id: "#BK-2836",
        artist: "Light Show Pro",
        artistAvatar: "https://i.pravatar.cc/40?img=7",
        category: "Lighting",
        date: "Apr 5, 2026",
        location: "Galle",
        amount: "LKR 20,000",
        status: "pending",
      },
      {
        id: "#BK-2815",
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        category: "Band",
        date: "Mar 14, 2026",
        location: "Colombo",
        amount: "LKR 15,000",
        status: "completed",
      },
      {
        id: "#BK-2788",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Feb 25, 2026",
        location: "Colombo",
        amount: "LKR 8,000",
        status: "completed",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "Rock Nation",
        artistAvatar: "https://i.pravatar.cc/40?img=8",
        rating: 5,
        comment:
          "The best corporate event entertainment we've had in years. Flawless!",
        date: "Mar 15, 2026",
      },
      {
        id: 2,
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        rating: 4,
        comment:
          "Very talented and punctual. Our guests were thoroughly impressed.",
        date: "Feb 26, 2026",
      },
    ],
  },
  {
    id: 7,
    name: "Dilan Silva",
    email: "dilan@email.com",
    joined: "Feb 2026",
    bookings: 2,
    totalSpent: "LKR 14,000",
    lastActive: "2d ago",
    status: "banned",
    avatar: "https://i.pravatar.cc/150?img=26",
    banReason:
      "Abusive messages sent to artist after booking. Reported by MC Royal on March 10, 2026.",
    bookingHistory: [
      {
        id: "#BK-2830",
        artist: "MC Royal",
        artistAvatar: "https://i.pravatar.cc/40?img=6",
        category: "MC",
        date: "Mar 9, 2026",
        location: "Colombo",
        amount: "LKR 5,000",
        status: "completed",
      },
      {
        id: "#BK-2802",
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        category: "Musician",
        date: "Feb 22, 2026",
        location: "Colombo",
        amount: "LKR 9,000",
        status: "completed",
      },
    ],
    reviews: [
      {
        id: 1,
        artist: "Alex Jeannn",
        artistAvatar: "https://i.pravatar.cc/40?img=1",
        rating: 1,
        comment:
          "Terrible. Did not deliver what was promised. Would not recommend.",
        date: "Feb 23, 2026",
        flagged: true,
      },
    ],
  },
];

// Mock bookings
export const mockBookings = [
  {
    id: "#BK-2841",
    customer: "Alex Jean",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=1",
    },
    location: "Colombo",
    bookings: 47,
    rating: 4.7,
    status: "confirmed",
    amount: "LKR 12,000",
    date: "Mar 28, 2026",
  },
  {
    id: "#BK-2840",
    customer: "Samantha Lee",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=5",
    },
    location: "Colombo",
    bookings: 47,
    rating: 4.7,
    status: "pending",
    amount: "LKR 8,500",
    date: "Apr 2, 2026",
  },
  {
    id: "#BK-2839",
    customer: "Rajan Patel",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=3",
    },
    location: "Colombo",
    bookings: 47,
    rating: 4.7,
    status: "completed",
    amount: "LKR 15,000",
    date: "Mar 20, 2026",
  },
  {
    id: "#BK-2838",
    customer: "Kavya Nair",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=9",
    },
    location: "Colombo",
    bookings: 47,
    rating: 4.7,
    status: "cancelled",
    amount: "LKR 6,000",
    date: "Mar 15, 2026",
  },
  {
    id: "#BK-2837",
    customer: "Tom Wilson",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=6",
    },
    location: "Kandy",
    bookings: 32,
    rating: 4.5,
    status: "confirmed",
    amount: "LKR 10,000",
    date: "Mar 30, 2026",
  },
  {
    id: "#BK-2836",
    customer: "Priya Menon",
    artist: {
      name: "Alex Jeannn",
      email: "alex@email.com",
      avatar: "https://i.pravatar.cc/40?img=7",
    },
    location: "Galle",
    bookings: 61,
    rating: 4.9,
    status: "pending",
    amount: "LKR 20,000",
    date: "Apr 5, 2026",
  },
];

// Dashboard stats
export const mockDashboardStats = {
  revenueThisMonth: "LKR 847K",
  revenueGrowth: 18,
  activeBookings: 142,
  bookingsGrowth: 18,
  verifiedArtists: 386,
  artistsGrowth: 18,
  totalCustomers: 2841,
  customersGrowth: 18,
};
